Disque 1 de A à B
Disque 2 de A à C
Disque 1 de B à C
Disque 3 de A à B
Disque 1 de C à A
Disque 2 de C à B
Disque 1 de A à B
Disque 4 de A à C
Disque 1 de B à C
Disque 2 de B à A
Disque 1 de C à A
Disque 3 de B à C
Disque 1 de A à B
Disque 2 de A à C
Disque 1 de B à C
Disque 5 de A à B
Disque 1 de C à A
Disque 2 de C à B
Disque 1 de A à B
Disque 3 de C à A
Disque 1 de B à C
Disque 2 de B à A
Disque 1 de C à A
Disque 4 de C à B
Disque 1 de A à B
Disque 2 de A à C
Disque 1 de B à C
Disque 3 de A à B
Disque 1 de C à A
Disque 2 de C à B
Disque 1 de A à B
